/* Indice du ressource pour BIG2DEMO */

#define MENU     0   /* Arbre menu */
#define T_BUREAU 3   /* TITLE dans l'arbre MENU */
#define T_FICHIER 4   /* TITLE dans l'arbre MENU */
#define T_FENETRES 5   /* TITLE dans l'arbre MENU */
#define M_INFOS  8   /* STRING dans l'arbre MENU */
#define M_FORMLIBRE 17  /* STRING dans l'arbre MENU */
#define M_ALERTE 18  /* STRING dans l'arbre MENU */
#define M_QUITTER 19  /* STRING dans l'arbre MENU */
#define M_WFORMPETIT 21  /* STRING dans l'arbre MENU */
#define M_WFORMGRAND 22  /* STRING dans l'arbre MENU */
#define M_WWIND  23  /* STRING dans l'arbre MENU */
#define M_WMENU  24  /* STRING dans l'arbre MENU */

#define BUREAU   1   /* Formulaire/Dialogue */
#define BU_IMG   1   /* BOX dans l'arbre BUREAU */
#define BU_BOXTXT 2   /* BOX dans l'arbre BUREAU */
#define BU_TXT1  3   /* STRING dans l'arbre BUREAU */
#define BU_TXT2  4   /* STRING dans l'arbre BUREAU */
#define BU_ICN   5   /* ICON dans l'arbre BUREAU */

#define FORMULAIRE 2   /* Formulaire/Dialogue */
#define CADRE1   3   /* BUTTON dans l'arbre FORMULAIRE */
#define FO_RBA1  4   /* BUTTON dans l'arbre FORMULAIRE */
#define FO_RBA2  5   /* BUTTON dans l'arbre FORMULAIRE */
#define CADRE2   6   /* BUTTON dans l'arbre FORMULAIRE */
#define FO_RBB1  7   /* BUTTON dans l'arbre FORMULAIRE */
#define FO_RBB2  8   /* BUTTON dans l'arbre FORMULAIRE */
#define FO_RBB3  9   /* BUTTON dans l'arbre FORMULAIRE */
#define FO_PUI   11  /* IMAGE dans l'arbre FORMULAIRE */
#define FO_BC1   12  /* BUTTON dans l'arbre FORMULAIRE */
#define FO_BC2   13  /* BUTTON dans l'arbre FORMULAIRE */
#define TXT1     15  /* FTEXT dans l'arbre FORMULAIRE */
#define TXT2     16  /* FTEXT dans l'arbre FORMULAIRE */
#define P_CONFIRME 17  /* BUTTON dans l'arbre FORMULAIRE */
#define P_AIDE   18  /* BOXTEXT dans l'arbre FORMULAIRE */
#define P_ANNULE 19  /* BUTTON dans l'arbre FORMULAIRE */
#define FO_PUT   20  /* BUTTON dans l'arbre FORMULAIRE */

#define POP_UP1  3   /* Formulaire/Dialogue */

#define POP_UP2  4   /* Formulaire/Dialogue */

#define INFOS    5   /* Formulaire/Dialogue */
#define INF_INFOS 11  /* BOXTEXT dans l'arbre INFOS */
#define INF_SORTIE 12  /* BUTTON dans l'arbre INFOS */
#define INF_MERCI 13  /* BOXTEXT dans l'arbre INFOS */

#define AIDE1    6   /* Formulaire/Dialogue */

#define PETITFORM 7   /* Formulaire/Dialogue */
#define PF_BC1   2   /* BUTTON dans l'arbre PETITFORM */
#define PF_BC2   3   /* BUTTON dans l'arbre PETITFORM */
#define PF_CHAMP1 4   /* FTEXT dans l'arbre PETITFORM */
#define PF_CHAMP2 5   /* FTEXT dans l'arbre PETITFORM */
#define PF_CHAMP3 6   /* FTEXT dans l'arbre PETITFORM */
#define PF_CHAMP4 7   /* FTEXT dans l'arbre PETITFORM */
#define PF_CONFIRME 8   /* BUTTON dans l'arbre PETITFORM */
#define PF_ANNULE 9   /* BUTTON dans l'arbre PETITFORM */
#define PF_AIDE  10  /* BOXTEXT dans l'arbre PETITFORM */
#define PF_APPLIQUE 11  /* BUTTON dans l'arbre PETITFORM */
#define PF_RAZ   12  /* BUTTON dans l'arbre PETITFORM */
#define PF_TRAME 13  /* BOX dans l'arbre PETITFORM */
#define PF_COLOR 14  /* BOX dans l'arbre PETITFORM */

#define GRANDFORM 8   /* Formulaire/Dialogue */
#define GF_RBA1  3   /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBA2  4   /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBA3  5   /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBA4  6   /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBB1  8   /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBB2  9   /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBB3  10  /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBB4  11  /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBC1  13  /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBC2  14  /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBC3  15  /* BUTTON dans l'arbre GRANDFORM */
#define GF_RBC4  16  /* BUTTON dans l'arbre GRANDFORM */
#define GF_BC1   17  /* BUTTON dans l'arbre GRANDFORM */
#define GF_BC2   18  /* BUTTON dans l'arbre GRANDFORM */
#define GF_PU1   19  /* BUTTON dans l'arbre GRANDFORM */
#define GF_PL    20  /* BUTTON dans l'arbre GRANDFORM */
#define GF_ICN   22  /* IMAGE dans l'arbre GRANDFORM */
#define GF_PU2   23  /* BUTTON dans l'arbre GRANDFORM */
#define GF_CONFIRME 24  /* BUTTON dans l'arbre GRANDFORM */
#define GF_ANNULE 25  /* BUTTON dans l'arbre GRANDFORM */
#define GF_AIDE  26  /* BOXTEXT dans l'arbre GRANDFORM */
#define GF_APPLIQUE 27  /* BUTTON dans l'arbre GRANDFORM */
#define GF_RAZ   28  /* BUTTON dans l'arbre GRANDFORM */

#define W_MENU   9   /* Arbre menu */
#define TW_BUREAU 3   /* TITLE dans l'arbre W_MENU */
#define TW_OPTIONS 4   /* TITLE dans l'arbre W_MENU */
#define TW_ALERTS 5   /* TITLE dans l'arbre W_MENU */
#define MW_INFOS 8   /* STRING dans l'arbre W_MENU */
#define MW_IMAGE 10  /* STRING dans l'arbre W_MENU */
#define MW_ALERTE 11  /* STRING dans l'arbre W_MENU */
#define MW_AL    13  /* STRING dans l'arbre W_MENU */

#define MHIERA   10  /* Formulaire/Dialogue */
#define MH_HISTO 3   /* STRING dans l'arbre MHIERA */

#define POPUP_ICN 11  /* Formulaire/Dialogue */

#define PU_LIBRE 12  /* Formulaire/Dialogue */
#define PUL_ALERT 3   /* STRING dans l'arbre PU_LIBRE */
#define PUL_WMENU 10  /* STRING dans l'arbre PU_LIBRE */

#define CONTACT  13  /* Formulaire/Dialogue */

#define AIDE2    14  /* Formulaire/Dialogue */

#define HIERWIND 15  /* Formulaire/Dialogue */
#define MWH_ICN0 1   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN1 2   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN2 3   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN3 4   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN4 5   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN5 6   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN6 7   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN7 8   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN8 9   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN9 10  /* STRING dans l'arbre HIERWIND */

#define MERCI    16  /* Formulaire/Dialogue */

#define TOOL     17  /* Formulaire/Dialogue */
#define TL_INV   1   /* BUTTON dans l'arbre TOOL */
#define TL_LEFT  2   /* BUTTON dans l'arbre TOOL */
#define TL_CENTER 3   /* BUTTON dans l'arbre TOOL */
#define TL_RIGHT 4   /* BUTTON dans l'arbre TOOL */
#define TL_FONT  5   /* BUTTON dans l'arbre TOOL */
#define TL_SIZE  6   /* BUTTON dans l'arbre TOOL */

#define SIZES    18  /* Formulaire/Dialogue */

#define FONTS    19  /* Formulaire/Dialogue */

#define TRAMES   20  /* Formulaire/Dialogue */

#define COULEURS 21  /* Formulaire/Dialogue */

#define ALERTE   0   /* Chaine d'alerte */

#define AL_ICONES 1   /* Chaine d'alerte */

#define AL_POINTEUR 2   /* Chaine d'alerte */

#define TITRE_PF 3   /* Chaine libre */

#define TITRE_GF 4   /* Chaine libre */

#define CHARGETXT 5   /* Chaine libre */

#define CHARGEIMG 6   /* Chaine libre */

#define TIT_TXT  7   /* Chaine libre */

#define TIT_IMG  8   /* Chaine libre */

#define TIT_MENU 9   /* Chaine libre */

#define TIT_HIST 10  /* Chaine libre */

#define INF_HIST 11  /* Chaine libre */

#define TITREACC 12  /* Chaine libre */

#define TW_ACC   13  /* Chaine libre */

#define BA_RB    14  /* Chaine libre */

#define BA_BC    15  /* Chaine libre */

#define BA_PU    16  /* Chaine libre */

#define BA_PUIM  17  /* Chaine libre */

#define BA_PUBX  18  /* Chaine libre */

#define BA_TG    19  /* Chaine libre */

#define BA_TC    20  /* Chaine libre */

#define BA_TD    21  /* Chaine libre */

#define BA_TI    22  /* Chaine libre */

#define BA_FNT   23  /* Chaine libre */

#define BA_SIZ   24  /* Chaine libre */

#define ICN_WN   0   /* Ic“ne libre */

#define ICN_WF   1   /* Ic“ne libre */
