/* Indices du fichier ressource pour BIG2INCL */

#define BIGALERTE        0   /* Formulaire/Dialogue */
#define AL_BKGR          0   /* BOX dans l'arbre BIGALERTE */
#define AL_MOVE          1   /* IBOX dans l'arbre BIGALERTE */
#define AL_ST1           2   /* STRING dans l'arbre BIGALERTE */
#define AL_ST2           3   /* STRING dans l'arbre BIGALERTE */
#define AL_ST3           4   /* STRING dans l'arbre BIGALERTE */
#define AL_ST4           5   /* STRING dans l'arbre BIGALERTE */
#define AL_ST5           6   /* STRING dans l'arbre BIGALERTE */
#define AL_BU1           7   /* BUTTON dans l'arbre BIGALERTE */
#define AL_BU2           8   /* BUTTON dans l'arbre BIGALERTE */
#define AL_BU3           9   /* BUTTON dans l'arbre BIGALERTE */
#define AL_IC            10  /* IMAGE dans l'arbre BIGALERTE */

#define BIGICN           1   /* Formulaire/Dialogue */

#define BIGARRM          2   /* Formulaire/Dialogue */
#define BA_BKGR          0   /* BOX dans l'arbre BIGARRM */
#define BA_LF            1   /* BOXCHAR dans l'arbre BIGARRM */
#define BA_RT            2   /* BOXCHAR dans l'arbre BIGARRM */

#define IMG_USER         3   /* Formulaire/Dialogue */
#define RBHN             1   /* ICON dans l'arbre IMG_USER */
#define RBHS             2   /* ICON dans l'arbre IMG_USER */
#define RBMN             3   /* ICON dans l'arbre IMG_USER */
#define RBMS             4   /* ICON dans l'arbre IMG_USER */
#define BCHN             5   /* ICON dans l'arbre IMG_USER */
#define BCHS             6   /* ICON dans l'arbre IMG_USER */
#define BCMN             7   /* ICON dans l'arbre IMG_USER */
#define BCMS             8   /* ICON dans l'arbre IMG_USER */
#define PUH              9   /* ICON dans l'arbre IMG_USER */
#define PUM              10  /* ICON dans l'arbre IMG_USER */

#define BIGARRS          4   /* Formulaire/Dialogue */
#define SC_BKGR          0   /* BOX dans l'arbre BIGARRS */
#define SC_UP            1   /* BOXCHAR dans l'arbre BIGARRS */
#define SC_DN            2   /* BOXCHAR dans l'arbre BIGARRS */

#define BIGLIST          5   /* Formulaire/Dialogue */
#define BL_BKGR          1   /* BOX dans l'arbre BIGLIST */
#define BL_S1            2   /* STRING dans l'arbre BIGLIST */
#define BL_S2            3   /* STRING dans l'arbre BIGLIST */
#define BL_S3            4   /* STRING dans l'arbre BIGLIST */
#define BL_S4            5   /* STRING dans l'arbre BIGLIST */
#define BL_S5            6   /* STRING dans l'arbre BIGLIST */
#define BL_S6            7   /* STRING dans l'arbre BIGLIST */
#define BL_S7            8   /* STRING dans l'arbre BIGLIST */
#define BL_S8            9   /* STRING dans l'arbre BIGLIST */
#define BL_BA            10  /* IBOX dans l'arbre BIGLIST */
#define BL_UP            11  /* BOXCHAR dans l'arbre BIGLIST */
#define BL_DN            12  /* BOXCHAR dans l'arbre BIGLIST */
#define BL_ASC           13  /* BOX dans l'arbre BIGLIST */
#define BL_SL            14  /* BOX dans l'arbre BIGLIST */

#define BIG_WIND         6   /* Formulaire/Dialogue */
#define BW_BKGR          0   /* BOX dans l'arbre BIG_WIND */
#define BW_SIZERUL       1   /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_CLOSER        2   /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_MOVER         3   /* BOXTEXT dans l'arbre BIG_WIND */
#define BW_SMALLER       4   /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_CYCLER        5   /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_FULLER        6   /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_SIZERUR       7   /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_INFO          8   /* BOXTEXT dans l'arbre BIG_WIND */
#define BW_BARRE         9   /* BOX dans l'arbre BIG_WIND */
#define BW_VBAR          10  /* BOX dans l'arbre BIG_WIND */
#define BW_UPARROW       11  /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_VELEV         12  /* BOX dans l'arbre BIG_WIND */
#define BW_VSLIDE        13  /* BOX dans l'arbre BIG_WIND */
#define BW_DNARROW       14  /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_SIZERDL       15  /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_HBAR          16  /* BOX dans l'arbre BIG_WIND */
#define BW_LFARROW       17  /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_HELEV         18  /* BOX dans l'arbre BIG_WIND */
#define BW_HSLIDE        19  /* BOX dans l'arbre BIG_WIND */
#define BW_RTARROW       20  /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_SIZERDR       21  /* BOXCHAR dans l'arbre BIG_WIND */
#define BW_WORK          22  /* IBOX dans l'arbre BIG_WIND */

#define GADGETS          7   /* Formulaire/Dialogue */
#define GA_SULH          1   /* ICON dans l'arbre GADGETS */
#define GA_CLOH          2   /* ICON dans l'arbre GADGETS */
#define GA_SMAH          3   /* ICON dans l'arbre GADGETS */
#define GA_CYCH          4   /* ICON dans l'arbre GADGETS */
#define GA_FULH          5   /* ICON dans l'arbre GADGETS */
#define GA_SURH          6   /* ICON dans l'arbre GADGETS */
#define GA_AUPH          7   /* ICON dans l'arbre GADGETS */
#define GA_SLVH          8   /* ICON dans l'arbre GADGETS */
#define GA_ADNH          9   /* ICON dans l'arbre GADGETS */
#define GA_SDLH          10  /* ICON dans l'arbre GADGETS */
#define GA_ALFH          11  /* ICON dans l'arbre GADGETS */
#define GA_SLHH          12  /* ICON dans l'arbre GADGETS */
#define GA_ARTH          13  /* ICON dans l'arbre GADGETS */
#define GA_SDRH          14  /* ICON dans l'arbre GADGETS */
#define GA_SULM          15  /* ICON dans l'arbre GADGETS */
#define GA_CLOM          16  /* ICON dans l'arbre GADGETS */
#define GA_SMAM          17  /* ICON dans l'arbre GADGETS */
#define GA_CYCM          18  /* ICON dans l'arbre GADGETS */
#define GA_FULM          19  /* ICON dans l'arbre GADGETS */
#define GA_SURM          20  /* ICON dans l'arbre GADGETS */
#define GA_AUPM          21  /* ICON dans l'arbre GADGETS */
#define GA_SLVM          22  /* ICON dans l'arbre GADGETS */
#define GA_ADNM          23  /* ICON dans l'arbre GADGETS */
#define GA_SDLM          24  /* ICON dans l'arbre GADGETS */
#define GA_ALFM          25  /* ICON dans l'arbre GADGETS */
#define GA_SLHM          26  /* ICON dans l'arbre GADGETS */
#define GA_ARTM          27  /* ICON dans l'arbre GADGETS */
#define GA_SDRM          28  /* ICON dans l'arbre GADGETS */

#define SELF             8   /* Formulaire/Dialogue */
#define FS_MOVE          1   /* IBOX dans l'arbre SELF */
#define FS_TITRE         2   /* STRING dans l'arbre SELF */
#define FS_PATH          3   /* BOXTEXT dans l'arbre SELF */
#define FS_SAISIE        4   /* FTEXT dans l'arbre SELF */
#define FS_BOXL          5   /* IBOX dans l'arbre SELF */
#define FS_LA            6   /* BOXCHAR dans l'arbre SELF */
#define FS_LP            21  /* BOXCHAR dans l'arbre SELF */
#define FS_BOX           22  /* BOX dans l'arbre SELF */
#define FS_RETOUR        23  /* BOXCHAR dans l'arbre SELF */
#define FS_BOXAR         24  /* IBOX dans l'arbre SELF */
#define FS_ARUP          25  /* BOXCHAR dans l'arbre SELF */
#define FS_ARDN          26  /* BOXCHAR dans l'arbre SELF */
#define FS_ASC           27  /* BOX dans l'arbre SELF */
#define FS_SLD           28  /* BOX dans l'arbre SELF */
#define FS_BOXF          29  /* IBOX dans l'arbre SELF */
#define FS_BF            30  /* BOX dans l'arbre SELF */
#define FS_FILTRE        31  /* TEXT dans l'arbre SELF */
#define FS_OK            32  /* BUTTON dans l'arbre SELF */
#define FS_ANN           33  /* BUTTON dans l'arbre SELF */

#define AIDE             9   /* Formulaire/Dialogue */

#define BIGNOT_RSC       0   /* Chaåne d'alerte */

#define NOT_WINDOW       1   /* Chaåne d'alerte */

#define EXITAUTO         2   /* Chaåne libre */
