/* Resource file indices for BIG2DEMO. */

#define MENU             0   /* Menu-tree */
#define T_BUREAU         3   /* TITLE in tree MENU */
#define T_FICHIER        4   /* TITLE in tree MENU */
#define T_FENETRES       5   /* TITLE in tree MENU */
#define M_INFOS          8   /* STRING in tree MENU */
#define M_FORMLIBRE      17  /* STRING in tree MENU */
#define M_ALERTE         18  /* STRING in tree MENU */
#define M_QUITTER        19  /* STRING in tree MENU */
#define M_WFORMPETIT     21  /* STRING in tree MENU */
#define M_WFORMGRAND     22  /* STRING in tree MENU */
#define M_WWIND          23  /* STRING in tree MENU */
#define M_WMENU          24  /* STRING in tree MENU */

#define BUREAU           1   /* Form/Dialog-box */
#define BU_IMG           1   /* BOX in tree BUREAU */
#define BU_BOXTXT        2   /* BOX in tree BUREAU */
#define BU_TXT1          3   /* STRING in tree BUREAU */
#define BU_TXT2          4   /* STRING in tree BUREAU */
#define BU_ICN           5   /* ICON in tree BUREAU */

#define FORMULAIRE       2   /* Form/Dialog-box */
#define CADRE1           3   /* BUTTON in tree FORMULAIRE */
#define FO_RBA1          4   /* BUTTON in tree FORMULAIRE */
#define FO_RBA2          5   /* BUTTON in tree FORMULAIRE */
#define CADRE2           6   /* BUTTON in tree FORMULAIRE */
#define FO_RBB1          7   /* BUTTON in tree FORMULAIRE */
#define FO_RBB2          8   /* BUTTON in tree FORMULAIRE */
#define FO_RBB3          9   /* BUTTON in tree FORMULAIRE */
#define FO_PUI           11  /* IMAGE in tree FORMULAIRE */
#define FO_BC1           12  /* BUTTON in tree FORMULAIRE */
#define FO_BC2           13  /* BUTTON in tree FORMULAIRE */
#define TXT1             15  /* FTEXT in tree FORMULAIRE */
#define TXT2             16  /* FTEXT in tree FORMULAIRE */
#define P_CONFIRME       17  /* BUTTON in tree FORMULAIRE */
#define P_AIDE           18  /* BOXTEXT in tree FORMULAIRE */
#define P_ANNULE         19  /* BUTTON in tree FORMULAIRE */
#define FO_PUT           20  /* BUTTON in tree FORMULAIRE */

#define POP_UP1          3   /* Form/Dialog-box */

#define POP_UP2          4   /* Form/Dialog-box */

#define INFOS            5   /* Form/Dialog-box */
#define INF_INFOS        11  /* BOXTEXT in tree INFOS */
#define INF_SORTIE       12  /* BUTTON in tree INFOS */
#define INF_MERCI        13  /* BOXTEXT in tree INFOS */

#define AIDE1            6   /* Form/Dialog-box */

#define PETITFORM        7   /* Form/Dialog-box */
#define PF_BC1           2   /* BUTTON in tree PETITFORM */
#define PF_BC2           3   /* BUTTON in tree PETITFORM */
#define PF_CHAMP1        4   /* FTEXT in tree PETITFORM */
#define PF_CHAMP2        5   /* FTEXT in tree PETITFORM */
#define PF_CHAMP3        6   /* FTEXT in tree PETITFORM */
#define PF_CHAMP4        7   /* FTEXT in tree PETITFORM */
#define PF_CONFIRME      8   /* BUTTON in tree PETITFORM */
#define PF_ANNULE        9   /* BUTTON in tree PETITFORM */
#define PF_AIDE          10  /* BOXTEXT in tree PETITFORM */
#define PF_APPLIQUE      11  /* BUTTON in tree PETITFORM */
#define PF_RAZ           12  /* BUTTON in tree PETITFORM */
#define PF_TRAME         13  /* BOX in tree PETITFORM */
#define PF_COLOR         14  /* BOX in tree PETITFORM */

#define GRANDFORM        8   /* Form/Dialog-box */
#define GF_RBA1          3   /* BUTTON in tree GRANDFORM */
#define GF_RBA2          4   /* BUTTON in tree GRANDFORM */
#define GF_RBA3          5   /* BUTTON in tree GRANDFORM */
#define GF_RBA4          6   /* BUTTON in tree GRANDFORM */
#define GF_RBB1          8   /* BUTTON in tree GRANDFORM */
#define GF_RBB2          9   /* BUTTON in tree GRANDFORM */
#define GF_RBB3          10  /* BUTTON in tree GRANDFORM */
#define GF_RBB4          11  /* BUTTON in tree GRANDFORM */
#define GF_RBC1          13  /* BUTTON in tree GRANDFORM */
#define GF_RBC2          14  /* BUTTON in tree GRANDFORM */
#define GF_RBC3          15  /* BUTTON in tree GRANDFORM */
#define GF_RBC4          16  /* BUTTON in tree GRANDFORM */
#define GF_BC1           17  /* BUTTON in tree GRANDFORM */
#define GF_BC2           18  /* BUTTON in tree GRANDFORM */
#define GF_PU1           19  /* BUTTON in tree GRANDFORM */
#define GF_PL            20  /* BUTTON in tree GRANDFORM */
#define GF_ICN           22  /* IMAGE in tree GRANDFORM */
#define GF_PU2           23  /* BUTTON in tree GRANDFORM */
#define GF_CONFIRME      24  /* BUTTON in tree GRANDFORM */
#define GF_ANNULE        25  /* BUTTON in tree GRANDFORM */
#define GF_AIDE          26  /* BOXTEXT in tree GRANDFORM */
#define GF_APPLIQUE      27  /* BUTTON in tree GRANDFORM */
#define GF_RAZ           28  /* BUTTON in tree GRANDFORM */

#define W_MENU           9   /* Menu-tree */
#define TW_BUREAU        3   /* TITLE in tree W_MENU */
#define TW_OPTIONS       4   /* TITLE in tree W_MENU */
#define TW_ALERTS        5   /* TITLE in tree W_MENU */
#define MW_INFOS         8   /* STRING in tree W_MENU */
#define MW_IMAGE         10  /* STRING in tree W_MENU */
#define MW_ALERTE        11  /* STRING in tree W_MENU */
#define MW_AL            13  /* STRING in tree W_MENU */

#define MHIERA           10  /* Form/Dialog-box */
#define MH_HISTO         3   /* STRING in tree MHIERA */

#define POPUP_ICN        11  /* Form/Dialog-box */

#define PU_LIBRE         12  /* Form/Dialog-box */
#define PUL_ALERT        3   /* STRING in tree PU_LIBRE */
#define PUL_WMENU        10  /* STRING in tree PU_LIBRE */

#define CONTACT          13  /* Form/Dialog-box */

#define AIDE2            14  /* Form/Dialog-box */

#define HIERWIND         15  /* Form/Dialog-box */
#define MWH_ICN0         1   /* STRING in tree HIERWIND */
#define MWH_ICN1         2   /* STRING in tree HIERWIND */
#define MWH_ICN2         3   /* STRING in tree HIERWIND */
#define MWH_ICN3         4   /* STRING in tree HIERWIND */
#define MWH_ICN4         5   /* STRING in tree HIERWIND */
#define MWH_ICN5         6   /* STRING in tree HIERWIND */
#define MWH_ICN6         7   /* STRING in tree HIERWIND */
#define MWH_ICN7         8   /* STRING in tree HIERWIND */
#define MWH_ICN8         9   /* STRING in tree HIERWIND */
#define MWH_ICN9         10  /* STRING in tree HIERWIND */

#define MERCI            16  /* Form/Dialog-box */

#define TOOL             17  /* Form/Dialog-box */
#define TL_INV           1   /* BUTTON in tree TOOL */
#define TL_LEFT          2   /* BUTTON in tree TOOL */
#define TL_CENTER        3   /* BUTTON in tree TOOL */
#define TL_RIGHT         4   /* BUTTON in tree TOOL */
#define TL_FONT          5   /* BUTTON in tree TOOL */
#define TL_SIZE          6   /* BUTTON in tree TOOL */

#define SIZES            18  /* Form/Dialog-box */

#define FONTS            19  /* Form/Dialog-box */

#define TRAMES           20  /* Form/Dialog-box */

#define COULEURS         21  /* Form/Dialog-box */

#define ALERT            0   /* Alert-string */

#define AL_ICONES        1   /* Alert-string */

#define AL_POINTEUR      2   /* Alert-string */

#define TITRE_PF         3   /* Free String */

#define TITRE_GF         4   /* Free String */

#define CHARGETXT        5   /* Free String */

#define CHARGEIMG        6   /* Free String */

#define TIT_TXT          7   /* Free String */

#define TIT_IMG          8   /* Free String */

#define TIT_MENU         9   /* Free String */

#define TIT_HIST         10  /* Free String */

#define INF_HIST         11  /* Free String */

#define TITREACC         12  /* Free String */

#define TW_ACC           13  /* Free String */

#define BA_RB            14  /* Free String */

#define BA_BC            15  /* Free String */

#define BA_PU            16  /* Free String */

#define BA_PUIM          17  /* Free String */

#define BA_PUBX          18  /* Free String */

#define BA_TG            19  /* Free String */

#define BA_TC            20  /* Free String */

#define BA_TD            21  /* Free String */

#define BA_TI            22  /* Free String */

#define BA_FNT           23  /* Free String */

#define BA_SIZ           24  /* Free String */

#define ICN_WN           0   /* Free Icon */

#define ICN_WF           1   /* Free Icon */
