/* Indices du fichier ressource pour BIG2_DOC */

#define MENU             0   /* Menu */
#define T_BIG            3   /* TITLE dans l'arbre MENU */
#define T_GENE           4   /* TITLE dans l'arbre MENU */
#define T_DEMO           5   /* TITLE dans l'arbre MENU */
#define T_CONCEPTS       6   /* TITLE dans l'arbre MENU */
#define T_FONCTIONS      7   /* TITLE dans l'arbre MENU */
#define T_METHODE        8   /* TITLE dans l'arbre MENU */
#define FONTE            11  /* STRING dans l'arbre MENU */
#define PRECEDENT        12  /* STRING dans l'arbre MENU */
#define SUIVANT          13  /* STRING dans l'arbre MENU */
#define SAUVER           14  /* STRING dans l'arbre MENU */
#define SDRIVER          16  /* STRING dans l'arbre MENU */
#define IMPRIMER         17  /* STRING dans l'arbre MENU */
#define QUITTER          19  /* STRING dans l'arbre MENU */
#define FIRSTOB          21  /* STRING dans l'arbre MENU */
#define M_COBJETS        54  /* STRING dans l'arbre MENU */
#define M_CFENETRES      55  /* STRING dans l'arbre MENU */
#define M_CFONCTIONS     56  /* STRING dans l'arbre MENU */
#define M_FGENE          58  /* STRING dans l'arbre MENU */
#define M_FFORM          59  /* STRING dans l'arbre MENU */
#define M_FFENE          60  /* STRING dans l'arbre MENU */
#define M_FDIVER         61  /* STRING dans l'arbre MENU */
#define M_SOURCE         63  /* STRING dans l'arbre MENU */
#define M_CONSEIL        64  /* STRING dans l'arbre MENU */

#define C_OBJETS         1   /* Formulaire/Dialogue */

#define C_FENE           2   /* Formulaire/Dialogue */

#define C_FONC           3   /* Formulaire/Dialogue */

#define F_GENERALES      4   /* Formulaire/Dialogue */

#define F_FORMULAIRES    5   /* Formulaire/Dialogue */

#define F_FENETRES       6   /* Formulaire/Dialogue */

#define F_DIVERSES       7   /* Formulaire/Dialogue */

#define SOURCE           8   /* Formulaire/Dialogue */

#define CONSEILS         9   /* Formulaire/Dialogue */

#define PRINT            10  /* Formulaire/Dialogue */
#define P_NBREL          2   /* FTEXT dans l'arbre PRINT */
#define P_OK             3   /* BUTTON dans l'arbre PRINT */
#define P_ANN            4   /* BUTTON dans l'arbre PRINT */

#define NOTMEM           0   /* Chaåne d'alerte */

#define NOTAID           1   /* Chaåne d'alerte */

#define NOTSPREF         2   /* Chaåne d'alerte */

#define NOTIMP           3   /* Chaåne d'alerte */

#define TITRE            4   /* Chaåne libre */

#define TITACC           5   /* Chaåne libre */

#define SELDRIVER        6   /* Chaåne libre */

#define WICN             0   /* Icìne libre */
